---
services:
  playwright:
    command: npx playwright test --ui --ui-host=0.0.0.0 --ui-port=8181
    expose:
      - 8181
    stdin_open: true   # keep stdin open so the UI process doesn't exit
    tty: true
